services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: roosevelt-backend

  frontend-user:
    build: ./frontend-user
    ports:
      - "3000:3000"
    container_name: roosevelt-frontend-user
    environment:
      - REACT_APP_API_URL=http://localhost:8080/roosevelt
    depends_on:
      - backend
